### ISSUE TITLE
BFTST

### ISSUE THREAD

**Issue by ShK0** [michalsc/Emu68#114]
CPUlvl=2, Mask=ffffffff Code=004b0000 SP=00460400 ISP=00460880
 Low: 00000000-00007fff High: ffffffff-fffffffe
Test: 00460000-004fffff Safe: ffffffff-fffffffe
BFTST (basic):
bftst/0000.dat (basic). 0...

004b0000 e8c0 7ed9     bftst    d0{d3:$19}
004b0004 2048     movea.l  a0,a0
004b0006 4afc     illegal
SR: expected 0000 -> 0004 but got 0000
Registers before:
D0: 00000022 D1: 00000000 D2: ffffffff D3: 3dbfffc0
D4: ffff0000 D5: 80008080 D6: 00010101 D7: aaaaaaaa
A0: 00000000 A1: 00000078 A2: 00007ff0 A3: 00007fff
A4: fffffffe A5: ffffff00 A6: 004aff00 A7: 00460400
SR:!0000      PC: 004b0000 ISP: 00460800 MSP: 00460880
T1=0 T0=0 S=0 M=0 X=0 N=0 Z!0 V=0 C=0
Registers after:
SR:!0000/2000 PC: 004b0006 ISP: 00460800 MSP: 00460880
T1=0 T0=0 S=0 M=0 X=0 N=0 Z!0 V=0 C=0
5 (0/2) S=2

**Comment by michalsc** [comment]
Fixed by 727b208
