### ISSUE TITLE
Fix enhanced 68020+ addressing modes

### ISSUE THREAD

**Issue by michalsc** [michalsc/Emu68#119]
Instead of fetching inner/outer offsets from instruction stream (it may be slow e.g. if memory is behind page fault handler), fetch the offsets during compile time and embed them in the code directly

**Comment by CrypticalCode0** [comment]
Do we keep track of register state? Because Xn, An might be altered in flight. if either are modified can affect the the resulting address.

and to be fair i expect the content of Xn to alter more often then not.

**Comment by michalsc** [comment]
Closing as it has been fixed a while ago.
