### ISSUE TITLE
Emu68 doesn't recognize SD 0x76 partition since release 25th Nov 2021

### ISSUE THREAD

**Issue by retrocrypta** [michalsc/Emu68#134]
Since last November 25, I do not know what has happened, SD partition as HD stopped working.  At boot,  the kickstart screen comes out and it does not recognize the HD of partition 0x76 of the SD, when it has always worked.

I have tried up to three different SD cards with the same result, it doesn't work, it doesn't even recognize the partitions with the HDToolBox Setup. 

It has not worked with the versions of the days 25th, 26th and the one of today the 27th. You have to go back to the one of the 24th for this to work correctly again.

I am going to try to download from git and recompile today's version and then report if it works or not.

**Comment by michalsc** [comment]
Please check with new nightly build. I have improved brcm-sdhc.device significantly.

**Comment by retrocrypta** [comment]
Hi ! 
Yes. Now is working again properly.
Thank You very much for your work
