### ISSUE TITLE
Configuration options

### ISSUE THREAD

**Issue by Tallguy297** [michalsc/Emu68#135]
I love your Emu68 Emulator and I am using it on my Amiga 600 and it is extremely fast.
Could you please outline the option for increasing the amount of fast memory and changing the CPU type?

Thank you,

**Comment by Tallguy297** [comment]
You mentioned in your Facebook post that the amount of fast memory can be changed in the cmdline.txt. Could you please explain the parameters to insert inside this file? I cannot find any documentation on this.

Thank you.

**Comment by michalsc** [comment]
The options available in Emu68 are now fully described on GitHub pages:

https://michalsc.github.io/Emu68/Options.html

Please have a look there and let me know if this document is easy to follow.
