### ISSUE TITLE
Mount ADF or boot from DF0

### ISSUE THREAD

**Issue by corasaniti** [michalsc/Emu68#139]
How can I mount a floppy in ADF format or boot directly from an ADF inserted in DF0?
Thanks in advance

**Comment by Tallguy297** [comment]
The easiest way without writing to an actual floppy disc is to mount a floppy Ram Disk (RAD:).
Mount the ADF file and do a Disc Copy. When done soft reboot the Amiga.

**Comment by michalsc** [comment]
Since Emu68 is only a CPU translation layer, it is not aware of ADF and it cannot actually support it as a floppy emulation.
