### ISSUE TITLE
Add emu68-tools as part of night builds

### ISSUE THREAD

**Issue by xinteksik** [michalsc/Emu68#142]
Please, add emu68-tools as part of night builds (Emucontrol, RTG driver, ...). Thanks

**Comment by michalsc** [comment]
The nightly builds of Emu68-tools are running, you can find them here: https://github.com/michalsc/Emu68-tools/releases/tag/nightly

Please let me know if such solution is satisfactory.

**Comment by xinteksik** [comment]
Solution is satisfactory, thanks.
