### ISSUE TITLE
WHDLoad not starting when JIT instruction depth == 1

### ISSUE THREAD

**Issue by TomCat666** [michalsc/Emu68#144]
WHDLoad doesn't start or crashes with a guru when you set the  JIT instruction depth to 1 with EmuControl.

note: if you start WHDLoad first and then drag the JIT instruction depth down to 1 while the whdload Banner is displayed then the game starts normally... so it is something with the whdload banner display/startup code.

**Comment by michalsc** [comment]
Fixed. Requires CCRD (CCR optimizer scan depth) to be set to 0, a.k.a. disabled.
