### ISSUE TITLE
No sound through HDMI

### ISSUE THREAD

**Issue by Tallguy297** [michalsc/Emu68#147]
Could you please explain the options I need to enable sound through the HDMI port, if available?

Thank you.

**Comment by michalsc** [comment]
The HDMI sound is not yet supported and does not belong to Emu68 project. I have however opened a new enhancement issue in Emu68-tools, where it actually belong: https://github.com/michalsc/Emu68-tools/issues/3#issue-1126894146

Feel free to comment there. I will work on that as soon as I have some spare time capacities.
