### ISSUE TITLE
Emu68 does not start if using a kickstart other than 3.2 on an A600

### ISSUE THREAD

**Issue by LemaruX** [michalsc/Emu68#148]
When using PiStorm on an A600, Emu68 will only work when using Kickstart 3.2 or 3.2.1. If any other kickstart version is used then Emu68 does not boot and just hangs on a black screen. 

After doing some testing with custom built ROMs, it appears this maybe caused by the exec.library contained in earlier kickstart versions. If you make custom 3.1 ROM using the exec.library taken from the 3.2.1 ROM then it boots without issue. 

Logs attached for KS3.1 which fails, and KS3.2.1 which works are attached. 

[A600 3.1 Fail.txt](https://github.com/michalsc/Emu68/files/8041453/A600.3.1.Fail.txt)
[A600 3.2.1 Working.txt](https://github.com/michalsc/Emu68/files/8041455/A600.3.2.1.Working.txt)

**Comment by SmoothAdmin** [comment]
Did you add the .rom file to the emu68 partition and did you update the config.txt file? It's also recommended you use the A1200 ROM and not machine specific. 

I am running the A1200.rom from 3.2.1 renamed to kick.rom and have my config.txt updated to reflect the name (last line) on my A2000 without issue.

**Comment by LemaruX** [comment]
> Did you add the .rom file to the emu68 partition and did you update the config.txt file? It's also recommended you use the A1200 ROM and not machine specific. 
> 
> I am running the A1200.rom from 3.2.1 renamed to kick.rom and have my config.txt updated to reflect the name (last line) on my A2000 without issue.

Yes, of course I added it to my Emu68 fat32 partition, and specified it in the config file. Though this does not matter as the issue occurs regardless of if using a mapped ROM, or a physical ROM.

Please note this is specifically regarding the Amiga 600, with ROMs earlier than Kickstart 3.1 (as per the big title, original post and attached debug logs). So having 3.2.1 working in an a2000 is not relevant to this issue at all.  Thanks.

**Comment by Neo2003** [comment]
Quite similar issue but not same
A1200 kick 3.1 works fine.
A1200 kick 3.1.4 all I get is purple screen. A600 3.1.4 same
I don't own and don't want 3.2, I just want 3.1.4 to work. I will try exec from 3.1 or if I can find one from 3.2

**Comment by michalsc** [comment]
The bug is fixed software-wise now. The issue was related to ghost data on D0..15 bus. Big Amigas are using pull-up resistors there, A500/A600 do not. I have tested Kickstarts from 2.0 up and with recent builds all of them were working properly.
