### ISSUE TITLE
bfchg, bfclr, bfextu, bftst instructions failing cputest

### ISSUE THREAD

**Issue by apolkosnik** [michalsc/Emu68#162]
bfchg, bfclr, bfextu, bftst fail on some of the extended addressing modes

**Comment by apolkosnik** [comment]
![image](https://user-images.githubusercontent.com/1034814/166568007-1efda209-66d5-4684-a789-2acded9ca4d8.png)
![image](https://user-images.githubusercontent.com/1034814/166568031-620b5dfd-1f7b-421b-b691-174860146af3.png)
![image](https://user-images.githubusercontent.com/1034814/166568065-d2ab4393-354b-4605-9228-e64a2497139d.png)
![image](https://user-images.githubusercontent.com/1034814/166568118-ec6eb8c5-1759-496b-9b98-9173b5f59909.png)

**Comment by apolkosnik** [comment]
It looks like there might be a problem with 4 byte reads and writes to wrap around address $fffffffe.
BFCHG seems to suffer from a different problem.

**Comment by michalsc** [comment]
Issue was caused by page fault handler which filtered out accesses crossing the 4G boundary. Pls check

**Comment by apolkosnik** [comment]
Confirmed fixed.
