### ISSUE TITLE
MOVEtoSR failing cputest

### ISSUE THREAD

**Issue by apolkosnik** [michalsc/Emu68#163]
movesr in extended addressing mode yields a wrong result.

**Comment by apolkosnik** [comment]
![image](https://user-images.githubusercontent.com/1034814/166568629-e2580ae5-7c78-4d1a-b5d1-f0e8aee1c5e3.png)

**Comment by apolkosnik** [comment]
![image](https://user-images.githubusercontent.com/1034814/172025443-9f8badfb-476b-42be-86af-7981ed833302.png)
Still happening

**Comment by apolkosnik** [comment]
The problem here seems that A7/SP gets modified for some reason

**Comment by michalsc** [comment]
Fixed by commit e962041c32a69d46ba6ad91a381f3f88e0b715f2
