### ISSUE TITLE
Grid in RTG mode

### ISSUE THREAD

**Issue by neuweiler** [michalsc/Emu68#167]
I'm using Emu68-pistorm-20220510-c5e995 and have set-up the RTG mode as outlined. It works but I get a grey grid overlay over the entire screen with certain resolutions (640x480, 1280x768). Max Colors don't make a difference. Fortunately 1920x1080 works fine, so it's not a big issue.

**Comment by michalsc** [comment]
you need to add some tool types to the Emu68-VC4 monitor icon: ```
VC4_SCALER=3
VC4_PHASE=64```

this should fix the grid.

**Comment by JackEx2022** [comment]
@michalsc 
Thanks that helps in my case too. Very impressive what your Emu68 is making with my tiny Amiga 500 *g* Thanks..
