### ISSUE TITLE
Autoboot with modified (added scsi.device) Kickstart 1.3 ROM

### ISSUE THREAD

**Issue by JackEx2022** [michalsc/Emu68#176]
Hello,
I've tried using my modified Kickstart 1.3 to boot from a (working) partition I already created under Kickstart 3.1.x, to no avail. On WinUAE, the ROM works as expected. WinUAE finds every virtual HDD and also the partition on the SD card when I mount it.
When I boot the Amiga with a WB1.3.3 floppy, the hard drive is not recognized at all. With WB2x's HDDToolBox and changed options (same entries as added in your [tutorial](https://michalsc.github.io/Emu68/tutorials/SD_Preparation.html) the tool didn't find a drive. Is there a way to work bring?

**Comment by michalsc** [comment]
if you have added scsi.device then it will not work with pistorm at all. Emu68 has it's own devices, namely brcm-sdhc.device (for pi3/pizero2) and brcm-emmc.device for pi4/cm4. As long as these are not added to the system, you will not see the hard drives at all.
