### ISSUE TITLE
PPC support?

### ISSUE THREAD

**Issue by juanpc2018** [michalsc/Emu68#181]
Amiga 4k had PPC CPU accelerator card, that allowed to Run AmigaOS4.x
it is interesting an Amiga PCB with dual CPU, 68k and PowerPC 604e @ 233MHz, / Sam460ex / PPC PA6T-1682M / P5020 / P5040

https://amiga.resource.cx/exp/cyberstormppc
http://phase5.a1k.org/index.html
https://translated.turbopages.org/proxy_u/de-en.en.020075d3-639a999b-ccf08960-74722d776562/https/www.amigawiki.org/doku.php?id=de:expansion:cpu:cyberstorm_ppc

https://youtu.be/AZL86gZr0LA

https://en.wikipedia.org/wiki/PowerUP_(accelerator)#Cyberstorm_PPC
https://en.wikipedia.org/wiki/PowerPC_600#PowerPC_604e
http://www.a-eon.com/?page=x5000
http://wiki.amiga.org/index.php?title=X5000
https://en.wikipedia.org/wiki/QorIQ#P5
https://en.wikipedia.org/wiki/AmigaOne_X1000
https://en.wikipedia.org/wiki/PWRficient
https://www.hyperion-entertainment.com/ 
https://www.amigaos.net/
https://en.wikipedia.org/wiki/Sam460ex - https://en.wikipedia.org/wiki/PowerPC_400#AMCC_460
http://www.sam4x0.com/sam460ex.html
https://www.acube-systems.biz/
https://www.amiga-shop.net/en/A-EON:.:42.html
http://www.ggsdata.se/index-en.php / Classic / AmigaOS

but probably would require faster Pi 4B+ or Faster Odroid N2+
or multiple Pi boards to emulate a 4-core PowerPC, like the Amiga X5000
AmigaOne 500 "Sam460ex" PPC 440 / 460EX core @ 1.115 GHz
X1000  PPC PA6T-1682M dual core 2Ghz.
X5000  PPC P5020 / P5040 two / quad core @ 2GHz / 2.4Ghz.
but... P5 CPUs dont have https://en.wikipedia.org/wiki/AltiVec

in my experience faster is better vs. more but slower cores, because interrupts, OS are Not designed for True Parallel processing with less/No interrupts.

https://fs-uae.net/docs/amigaos-4-1
http://zero.eik.bme.hu/~balaton/qemu/amiga/
https://www.hyperion-entertainment.com/index.php/where-to-buy/direct-downloads/174-amigaos-41-final-edition-for-classic

AmigaOS4 does Not Boot directly on older Apple PowerMac G5, requires Qemu / WinUAE / LinuxPPC/OSX Sorbet 10.5.9
but does Boot directly on older Amiga A3000 / A4000 with PPC Cyberstom CPU board.
X1000 / X5000 require a different CD Image / Installer "No Classic" included with HW purchase / registration.
Different PowerPC CPUs require different installers. 
Unknown if Classic installer or X5000 installer Boot directly on a Newer Raptor Talos II "dual cpu" / BlackBird "single cpu"
https://www.raptorcs.com/content/base/products.html

**Comment by michalsc** [comment]
The PowerPC emulation is beyond scope of this project. Maybe, somewhere in the future, when Emu68 is complete. But it is definitely not for now or for following two years.
