### ISSUE TITLE
Emu68-pistorm32lite-20230124-ebe92e.zip kernel pistorm32 lite green screen roms

### ISSUE THREAD

**Issue by macphreak4evr** [michalsc/Emu68#195]
newest build for pistorm32lite results in green screens no matter  what rom is copied.  reverted to 15th Jan build and works fine. 

note this is only the Emu68-pistorm32lite file that causes this, once i copy the older one over it works flawlessly.  

can someone else please test and verify this for this issue.  so far i have tested TWO pistorm32's and both did the same thing. highres photo attached of green screen with 24/1/2023 build
![IMG_6578](https://user-images.githubusercontent.com/76854336/217126585-5106881e-1ea3-456d-81c0-9b15c889428b.JPG)

**Comment by ziggystar12** [comment]
Same issue here. Works fine on 3B+ or Zero 2.

**Comment by michalsc** [comment]
Closing. Please reopen if this happens with official releases (1.0.4 at the moment)
