### ISSUE TITLE
Emu68-pistorm32lite and pi4b brcm-sdhc.device

### ISSUE THREAD

**Issue by Olherlin** [michalsc/Emu68#196]
Hello, the brcm-sdhc.device is not recognized by hdtoolbox when trying to format the card, whatever the version of Emu68-pistorm32lite and kickstart. Partitions are recognized if previously created using a pi3.

**Comment by luvwagn** [comment]
Brcm-emmc.device on 4b ?

**Comment by krug3rf** [comment]
> Brcm-emmc.device on 4b ?

No, it's really specific with the Pi4b and a SDHC card, when you want to build your own installation from scratch.
HDTOOLBOX is blind and don't find any partition from brm-sdhc.device
Partitions coud only usable when partitions have been performed before with a Pi2W or Pi3x

**Comment by Olherlin** [comment]
The latest nightly did not solved the issue.

**Comment by pcotter72** [comment]
replace brcm-sdhc.device with brcm-emmc.device IF using a Pi4/CM4

**Comment by Olherlin** [comment]
I will try with brcm-emmc.device tonight and report. Thank you

**Comment by krug3rf** [comment]
> replace brcm-sdhc.device with brcm-emmc.device IF using a Pi4/CM4

Oh
Without EMMC on Pi4 we must use brcm-emmc.device to use partition on SDHC card.

**Comment by Olherlin** [comment]
brcm-emmc.device works with pi4B.
