### ISSUE TITLE
Emu68 recognize no partitions on Pistorm32 with pi4

### ISSUE THREAD

**Issue by bbuehrig** [michalsc/Emu68#205]
There is a problem with the latest nightly build from 10. March 23. In HDTools with brcm-emmc.device no partitions will be recognized. With the nightly build from 3. March it is working.

**Comment by AdamENESS** [comment]
I get this if I had another HDD plugged into the IDE connector on the 1200.

It also made the PIStorm less stable with a HDD plugged in.

**Comment by amyren1966** [comment]
CaffeineOS 917 is based on the 10.march build and the SD card is shown in HDToolBox both under the brcm-emmc.device v1.0 as well as the brcm-sdhc.device v1.2
And I do have the internal HDD still plugged in.
