### ISSUE TITLE
Insertion or Removal of PCMCIA + CF-Card results in hang

### ISSUE THREAD

**Issue by luvwagn** [michalsc/Emu68#207]
Booting with 512MB CF-Card in PCMCIA slot works fine.  Hot removal or hot insertion, however, will hang emu68k.

Build: Latest "nightly" with Pi4 fixes
Amiga 1200 + RPi 4B 8GB
Kickstart: 46.143
Workbench: 45.194

**Comment by LemaruX** [comment]
@luvwagn the issues are NOT the same.

**Comment by TomCat666** [comment]
This is fixed with latest beta. Can be closed.
