### ISSUE TITLE
Latest nightly poor boot perf & aga mk3 issues / 20230424-420538

### ISSUE THREAD

**Issue by mzryz** [michalsc/Emu68#211]
Hi,

I haven't checked any nightlies released between this and the last official beta. Going from the official beta to this nightly 24th April 23 results in: 

* 60 seconds+ boot to desktop (10 seconds in official beta 04 March)
* Doing a sysinfo test shows CPU performance and drive performance are the same as official beta 04 March though.
* Indivision AGA MK3 is freaking out? Display is flickering, moving up/down in screen lines, jittering. During loading sequences.

Previously, the jittering up/down with indivision was *only* happening when running something intensive, like Ibrowse accessing SSL websites. For an example of this behavior please see my video: https://drive.google.com/file/d/10lafk3GZwfH_0oiBIXpfl9OeRwe-wTCb/view?usp=sharing
(I am not sure if that requires it's own issue log, but seems to be related and massively increased by this latest nightly, it would be nice if this problem went away entirely, even when running Ibrowse/SSL)

Pistorm32-lite / Pi3 A

**Comment by michalsc** [comment]
I will revert last commit. it turned out to be a bad idea to adjust arm and core clocks only

**Comment by mzryz** [comment]
@michalsc I was curious how an accelerator could affect the display with indivision aga MK3, so I asked Jens on his forum, this is his reply, I hope it may help:

![Screenshot_20230425-123537](https://user-images.githubusercontent.com/23113373/234265310-e9d753a8-8713-4780-82ef-265a5ff5c0a4.png)

**Comment by michalsc** [comment]
Well, unfortunately this comment from Jens is plain wrong. Emu68 does not hit any registers by itself, as Emu68 provides CPU emulation **only**. What is hitting registers is AmigaOS...

**Comment by michalsc** [comment]
Closing the issue - the nightly build is just broken
