### ISSUE TITLE
Missing function: parsing and renaming of repeated partition names

### ISSUE THREAD

**Issue by FerryA1** [michalsc/Emu68#214]
The usual way a storage device driver works on Amiga is to check for repeated partition names when adding them to the DOS device list and, if there are, rename them, usually by adding a "_1", "_2", etc. to the end of the name, and the Emu68 device driver in charge of the RPi's SD (I don't know about the one for the eMMC) does not do this.

**Comment by michalsc** [comment]
The conflict avoidance is not implemented in both brcm-emmc and brcm-sdhc.

**Comment by michalsc** [comment]
Name conflict avoidance is implemented now in both brcm-emmc and brcm-sdhc.
