### ISSUE TITLE
sound from rtg

### ISSUE THREAD

**Issue by martingclark** [michalsc/Emu68#222]
Is there a way to get sound out the pi hdmi direct to monitor when using rtg ? ive just realised that when using rtg my other monitor will have no picture (expected) but the sound comes from it whilst the picture is on the rtg displaybut no sound

**Comment by LemaruX** [comment]
No, that's now how RTG works as RTG is graphics only. All sound will come from Paula via the native sound outputs on the Amiga. Simple solution would be to connect speakers to the Amiga.

**Comment by michalsc** [comment]
This is not an issue. Emu68 does not emulate amiga audio or anything else from the chipset. For that reason the audio is always on the Chinch analog output from Amiga.
