### ISSUE TITLE
File copying using Browser II (a file manager)

### ISSUE THREAD

**Issue by martingclark** [michalsc/Emu68#223]
weird issue here, Same workbench i cant copy files from one partition to another with the pistorm32lite installed using Browser II, but swap out the card for a tf1260 and Browser II then works just fine, All other copy programs seem to work fine just browser II doesn't, but definitely the problem only exists when using the pistorm.

Anyone any ideas ?

**Comment by LemaruX** [comment]
What error message are you getting? 
Are you trying to copy to the SD card in the Pi? If so you need to set it as read/write by adding the below to the cmdline.txt file (note this file must contain only a single line of text).


`sd.unit0=rw emmc.unit0=rw`

(sd.unit0 is for the Pi Zero2/3a/3b and emmc.unit0 is for the Pi4/CM4. You can have both commands without issue though. Adjust the unit number as required)

**Comment by martingclark** [comment]
> What error message are you getting? Are you trying to copy to the SD card in the Pi? If so you need to set it as read/write by adding the below to the cmdline.txt file (note this file must contain only a single line of text).
> 
> `sd.unit0=rw emmc.unit0=rw`
> 
> (sd.unit0 is for the Pi Zero2/3a/3b and emmc.unit0 is for the Pi4/CM4. You can have both commands without issue though. Adjust the unit number as required)

Its when copying from/to/between amiga native hard disk drive partitions, The same process when the tf1260 is installed works perfectly using the same file manager and exactly the same workbench setup, only thing i swap out to reproduce or not have the issue is the pistorm (using either pi3 or pi4 gives same issue), is there anything that snoopdos may help with, ive attached a screenshots, If there is anything else you'd like me to try to maybe of assistance to you resolving it im only to glad to help. tried to send short video but was too big.

Kind regards, Martin


![IMG_20230625_165802](https://github.com/michalsc/Emu68/assets/6729129/5a38a9c2-d1b7-4aeb-bebf-54d5d1577f35)
![IMG_20230625_165734](https://github.com/michalsc/Emu68/assets/6729129/118858dd-f1ab-4920-9d4d-8a60eabf9dae)
![IMG_20230625_165643](https://github.com/michalsc/Emu68/assets/6729129/1e04f35e-eefa-4300-a07b-636febf2a9fd)
![IMG_20230625_165853](https://github.com/michalsc/Emu68/assets/6729129/094f21d8-88ca-4ba5-a221-682b44246a61)
![IMG_20230625_165847](https://github.com/michalsc/Emu68/assets/6729129/3202c05e-5089-4029-ae1d-2045d089a8
![IMG_20230625_165853](https://github.com/michalsc/Emu68/assets/6729129/a2df9724-a79b-448f-82b5-476bae9a77f3)
![IMG_20230625_165847](https://github.com/michalsc/Emu68/assets/6729129/e1a6a059-6268-4ec7-a1cd-bb34ae2ea443)
cc)
![IMG_20230625_165802](https://github.com/michalsc/Emu68/assets/6729129/89e801db-39ea-425e-8fb2-c9884f91eb4c)

**Comment by LemaruX** [comment]
Is there any reason you are not using the Pi's SD card rather than the onboard IDE? The IDE is extremely slow in comparison 

Again, this is something that would be better posted on discord in one of the support channels, and would get a better response there.

**Comment by martingclark** [comment]
No reason other than my workbench is rather large and i have tried the microsd route before and find the amiga ide fast enough and less prone to corruption, sd cards in general are less reliable imho

**Comment by martingclark** [comment]
Could the cause be the fact that pistorm uses the ROM copied into its ram where when the tf1260 is in use its the physical rom, tried to run pistorm without specifying a rom as thought it would use the physical rom but then amiga wouldnt boot (3.2.2 in both cases)

**Comment by michalsc** [comment]
Many thanks to @mras0 who has identified the issue. It is not Emu68 related, the problem is with BrowserII itself. It fails when AmigaOS has too much memory.

Solution: Limit amount of memory available to AmigaOS/Emu68 by adjusting ``total_mem`` in config.txt.

**Comment by mras0** [comment]
Another option (at your own risk) is to change the byte at offset $129de in the BrowserII executable (v. 3.09 or patch v. 3.10) from $6c to $60. That also seems to work around the issue without having to reduce the Emu68 memory.

**Comment by martingclark** [comment]
> Another option (at your own risk) is to change the byte at offset $129de in the BrowserII executable (v. 3.09 or patch v. 3.10) from $6c to $60. That also seems to work around the issue without having to reduce the Emu68 memory.

Thanks for finding this issue in the first place, i saw a comment on github for changing the executable of browser II, that hex value change is at the same address on 3.09 and the 3.10 and ive changed it, it seems to work perfectly with full pistorm ram available
