### ISSUE TITLE
Feature Request: EmuControl to send values to ENV:

### ISSUE THREAD

**Issue by AmiKit** [michalsc/Emu68#224]
It would be cool if the EmuControl could also send selected values to ENV:, preferably the temperature, so I could display it on DOpus Magellan screen bar, for instance. I hope that MUI offers such feature.

**Comment by AmiKit** [comment]
Emu68EnvCX solved that. Thanks Flype!!

**Comment by michalsc** [comment]
I'm closing as solved :)
