### ISSUE TITLE
Enhancement: Alternative firmware to use PiStorm as just a memory expansion.

### ISSUE THREAD

**Issue by G4DDS** [michalsc/Emu68#228]
A far more useful alternative to completely disabling the PiStorm (using the special firmware) would be firmware which just turns it into a memory expansion where the amount of RAM can be configured.

**Comment by lovrenco** [comment]
I think I asked about this too, a long time ago.
If possible that would instantly solve compatibility issues.
😁

**Comment by captain-amygdala** [comment]
@michalsc , please close this issue. As I stated before this "issue" can't be resolved by emu68 as it is hardware related.
@lovrenco please reopen the issue in the correct project (pistorm)

**Comment by michalsc** [comment]
Closing as suggested by @captain-amygdala. Unrelated to Emu68.
