### ISSUE TITLE
ADDX.W

### ISSUE THREAD

**Issue by ghost** [michalsc/Emu68#25]
CPUlvl=2, Mask=ffffffff Code=004b0000 SP=00460400 ISP=00460880
 Low: 00000000-00007fff High: ffffffff-fffffffe
Test: 00460000-004fffff Safe: ffffffff-fffffffe
ADDX.W (basic):
addx.w/0000.dat (basic). 0...
addx.w/0001.dat (basic). 390...

004b0000 d742     addx.w   d2,d3
004b0002 4afc     illegal
S 004603fc 71.d2.fc.00.02.00*24.13.78.00.00.2c.00.fa.00.00.a9.23.9f.73
D 0000007d a6.aa.c6.00.00.dc*d6.00.00.00.81.c1.2d.68.ec.60.0b.00.00.92
SR: modified 001f -> 0000 but expected 0011
Registers before:
D0: 000001e4 D1: 00000000 D2: 7fff776f D3:*087fffff
D4: 85551090 D5: 80129292 D6: 00040404 D7: 8d46ab88
A0: 00000000 A1: 00000080 A2: 00008003 A3: 0000ffff
A4: fffffffe A5: ffffff00 A6: 004afeff A7: 004603fe
SR:!001f      PC: 004b0000 ISP: 00460800 MSP: 00460880
T1=0 T0=0 S=0 M=0 X!1 N*1 Z*1 V*1 C!1
Registers after:
D0: 000001e4 D1: 00000000 D2: 7fff776f D3:*087f776f
SR:!0000/2000 PC: 004b0002 ISP: 00460800 MSP: 00460880
T1=0 T0=0 S=0 M=0 X!0 N*0 Z*0 V*0 C!0
OK: No exception generated
526 (1/2) S=196

**Comment by ShK0** [comment]
Fixed in Emu68-pistorm-20211008-724d95.
