### ISSUE TITLE
PiStorm32-Emu68-WhichAmiga causes immediate crash running from WorkBench

### ISSUE THREAD

**Issue by F1Lupo** [michalsc/Emu68#255]
PiStorm32 with 3A+-Emu68- Amiga OS2.2.2
-Issue happens with Nov18/23 firmware.

-runs fine when launched from Shell

**Comment by mras0** [comment]
Should be fixed in 1.0 (works for me)

**Comment by michalsc** [comment]
Fixed since 1.0
