### ISSUE TITLE
Proper MMU handling for Fusion Mac emulator

### ISSUE THREAD

**Issue by tkurbad** [michalsc/Emu68#260]
Hi,

It would be great to have the ability to run the upcoming Fusion4 Mac emulator on PiStorm.

According to Jim Drew, the developer of Fusion, the greatest barrier to doing so atm is that Emu68 crashes on basic MMU access.
Apparently, a real MC68ECx0 as well as WinUAE, when set to 68040 w/o MMU does not crash.

I don't know how much effort it would be to fix this. However, I'm already a Patreon and would gladly raise my bounty to see Fusion on PiStorm eventually. :-)

Thanks!

**Comment by michalsc** [comment]
Please check todays nightly build :)

**Comment by JimDrewGH** [comment]
Well, that's fantastic news!  I will update my 2 year old EMU68 and check this out!  :)
