### ISSUE TITLE
Software failure for Videocore on Kickstart 3.1

### ISSUE THREAD

**Issue by mja65** [michalsc/Emu68#267]
Using Pistorm32lite on A1200 and using Kickstart 3.1 (Commodore version, 40.68) with the videocore driver results in software failure on booting (Program Failed error #8000000B) when the screen is set to a RTG mode. However, the exact same set up using Kickstart 3.2. (47.111) works and boots to workbench. This is from a user via the Commodore Amiga Facebook group, however, I've been able to replicate the problem based on a disk image of their set up.

Steps to reproduce:
1. Install Workbench 3.1
2. Install videocore.card file from emu-tools (I used the file from 11 January 2024 since I had this on hand)
3. Install P96 (RTG library version 43.538, PicassoAPI 2.455) per instructions here (https://michalsc.github.io/Emu68/tutorials/P96_Setup.html)
4. Set up screen modes - Also note that when following the instructions on occasion when you try and add the board to Picasso96prefereces no board is actually available. I ended up doing this switching to the 3.2 ROM.
5. Reboot

This will result in the error described above. However, if I replace the kickstart with 3.2 (as well as adding the 3.1 version of workbench.library and icon.library to LIBS given it's no longer in the ROM) and reboot workbench loads into a RTG screen

**Comment by MPC7500** [comment]
Hello,

I am using AmigaOS 3.2.2.1 with KickROM 47.111 and P96 V3.4.1. I also get the error message “(Program Failed error #8000000B)”.

Is there a solution/workaround in the meantime?

**Comment by elerion64** [comment]
Hi
Issue is with Emu68-VC4.card/Videocore.card from the latest nightlies. (Workaround is to replace these files with the ones form the older builds.)
Since this concerns emu68-tools. You might want to close this issue, and reopen in emu68-tools.
E.

**Comment by michalsc** [comment]
New driver needs new version of Emu68 (not released yet). Issue will solve itself with next Emu68 release.
