### ISSUE TITLE
Add 16 bit AHI capable sound support

### ISSUE THREAD

**Issue by sacredbanana** [michalsc/Emu68#281]
As decent as 14 bit Paula can sound, it can't compete with a 16 bit sound card. Would it be feasible to add an AHI capable sound device and have it output via the HDMI port?

**Comment by michalsc** [comment]
This is wrong place for this enhancement. It shall go to Emu68-tools repository. In fact, it already exists there:
https://github.com/michalsc/Emu68-tools/issues/3
