### ISSUE TITLE
RTE

### ISSUE THREAD

**Issue by ShK0** [michalsc/Emu68#92]
CPUlvl=2, Mask=ffffffff Code=004b0000 SP=00460400 ISP=00460880
 Low: 00000000-00007fff High: ffffffff-fffffffe
Test: 00460000-004fffff Safe: ffffffff-fffffffe
RTE (basic):
rte/0000.dat (basic). 0...

004b0000 4e73     rte
004b0002 2048     movea.l  a0,a0
004b0004 4afc     illegal
004b8000 2048     movea.l  a0,a0
004b8002 4afc     illegal
P 00460800 00.4b.00.00.00.20*00.00.00.4b.80.00.37.a0.31.e7.f3.7f.00.64
  00460800 00.00.00.00.20.00*08.05.8b.12.00.00.00.4b.80.02.00.10.00.64
B 004b8000 00.b1.00.00.c5.a9*20.48.4a.fc.e3.00.00.01.02.dd.00.10.00.26
SR: expected 2000 -> 2000 but got 0000
Exception: expected 14 but got 4 (or no exception)
Registers before:
D0: 00000010 D1: 00000000 D2: ffffffff D3: ffffff00
D4: ffff0000 D5: 80008080 D6: 00010101 D7: aaaaaaaa
A0: 00000000 A1: 00000078 A2: 00007ff0 A3: 00007fff
A4: fffffffe A5: ffffff00 A6: 004aff00 A7: 00460400
SR:!2000      PC: 004b0000 ISP: 00460800 MSP: 00460880
T1=0 T0=0 S!1 M=0 X=0 N=0 Z=0 V=0 C=0
Registers after:
SR:!0000/2000 PC: 004b8002 ISP: 00460800 MSP: 00460880
T1=0 T0=0 S!0 M=0 X=0 N=0 Z=0 V=0 C=0
31 (0/2) S=15 E04=1 E08=16

**Comment by michalsc** [comment]
fixed by 152cff0
