### ISSUE TITLE
SUBX.W

### ISSUE THREAD

**Issue by ShK0** [michalsc/Emu68#99]
CPUlvl=2, Mask=ffffffff Code=004b0000 SP=00460400 ISP=00460880
 Low: 00000000-00007fff High: ffffffff-fffffffe
Test: 00460000-004fffff Safe: ffffffff-fffffffe
SUBX.W (basic):
subx.w/0000.dat (basic). 0...

004b0000 9140     subx.w   d0,d0
004b0002 2048     movea.l  a0,a0
004b0004 4afc     illegal
SR: modified 0000 -> 0004 but expected 0000
Registers before:
D0:*00000010 D1: 00000000 D2: ffffffff D3: ffffff00
D4: ffff0000 D5: 80008080 D6: 00010101 D7: aaaaaaaa
A0: 00000000 A1: 00000078 A2: 00007ff0 A3: 00007fff
A4: fffffffe A5: ffffff00 A6: 004aff00 A7: 00460400
SR:!0000      PC: 004b0000 ISP: 00460800 MSP: 00460880
T1=0 T0=0 S=0 M=0 X=0 N=0 Z!0 V=0 C=0
Registers after:
D0:*00000000 D1: 00000000 D2: ffffffff D3: ffffff00
SR:!0004/2004 PC: 004b0004 ISP: 00460800 MSP: 00460880
T1=0 T0=0 S=0 M=0 X=0 N=0 Z!1 V=0 C=0
1 (0/2) S=0

**Comment by ShK0** [comment]
Emu68-pistorm-20210929-066949

CPUlvl=2, Mask=ffffffff Code=004b0000 SP=00460400 ISP=00460880
 Low: 00000000-00007fff High: ffffffff-fffffffe
Test: 00460000-004fffff Safe: ffffffff-fffffffe
SUBX.W (basic):
subx.w/0000.dat (basic). 0...

004b0000 9340     subx.w   d0,d1
004b0002 4afc     illegal
SR: modified 001f -> 0008 but expected 0019
Registers before:
D0: 000000a0 D1:*00000000 D2: 7fff7f67 D3: 3fffb7c0
D4: 9fb7c080 D5: 00010101 D6: 00020202 D7: 05e65f32
A0: 00000000 A1: 00000078 A2: 00007ff0 A3: 00007fff
A4: fffffffe A5: ffffff00 A6: 004aff00 A7: 00460400
SR:!001f      PC: 004b0000 ISP: 00460800 MSP: 00460880
T1=0 T0=0 S=0 M=0 X!1 N=1 Z*1 V*1 C!1
Registers after:
D0: 000000a0 D1:*0000ff5f D2: 7fff7f67 D3: 3fffb7c0
SR:!0008/2008 PC: 004b0002 ISP: 00460800 MSP: 00460880
T1=0 T0=0 S=0 M=0 X!0 N=1 Z*0 V*0 C!0
OK: No exception generated
34 (1/2) S=16

**Comment by michalsc** [comment]
Fixed in 14edb74
